title: How to Target Email Clients
description: >- # this means to ignore newlines until "baseurl:"
  Crowdsourced email development techniques for singling out email clients and platforms.
baseurl: ""
url: "https://howtotarget.email"
github_repository: https://github.com/dylanatsmith/howtotarget
author:
  name: Dylan Smith
  twitter: dylanatsmith
  github: dylanatsmith
  email: dylan@dylanatsmith.com

# Build settings
# theme: minima

# For markdown
kramdown:
  # Autogenerate IDs for headings
  # Used for anchor links
  auto_ids: true
  auto_id_stripping: true

# SCSS
sass:
  sass_dir: assets/scss
  style: compressed

plugins:
  - jekyll-last-modified-at
  - jekyll-timeago

jekyll_timeago:
  depth: 1
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
